### ISSUE TITLE
Habitat Installation 

### ISSUE THREAD

**Issue by mohit939** [chef-partners/vsts-habitat#1]
I have installed habitat with VSTS and habitat installed at this location  /tmp/hab , but when I am trying to run "hab setup" command its not working, its showing hab command not found.

After coping that hab* file to /usr/local/bin/ from /tmp/ it is working fine.

can someone help me to solve this issue.

**Comment by jjasghar** [comment]
That sounds like a pathing issue. Can you eco your $PATH here?

**Comment by mohit939** [comment]
ya it was pathing issue, I resolved it by editing the install-habitat.js file.
